title: Collapsed Space
theme: just-the-docs
# Color scheme supports "light" (default) and "dark"
color_scheme: dark

url: https://hutsonphd.github.io/collapsed.space

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
