title: Collapsed Space
theme: just-the-docs

url: https://hutsonphd.github.io/collapsed.space/

color_scheme: custom
logo: "/assets/svg/logo.svg"
favicon_ico: "/assets/svg/favicon.svg"

callouts:
  abstract:
    title: "  Abstract"
    color: blue
  important:
    title: "  Important"
    color: red
  insight:
    title: "  Insight"
    color: yellow
  critical:
    title: "  Critical"
    color: red
  question:
    title: " Question"
    color: blue
  notable:
    title: " Notable"
    color: yellow
search_enabled: true
heading_anchors: true
nav_enabled: true

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"
